name: test

on:
  push:

jobs:
  start:
    name: Setup Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initializes
        run: &echoHello echo Hello,World!!
      
      - name: Hello, World!!-1
        run: *echoHello

      - name: Hello, World!!-2
        run: *echoHello
