name: Test

on: push
jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initializes
        run: &echoHello
      
      - name: Hello, World!!-1
        run: *echoHello

      - name: Hello, World!!-2
        run: *echoHello
