name: Test

on:
  push:

jobs:
  start:
    name: Setup Ubuntu
    runs-on: ubuntu-latest
    env:
      ECHO_HELLO: echo "Hello, World!!"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Hello, World!!-1
        run: $ECHO_HELLO

      - name: Hello, World!!-2
        run: $ECHO_HELLO
